=== SanSay157/IT8/IT.Web/Metadata/x-net-server-objects-schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
	CROC XML Framework .NET
	
	XSD-схема определения конфигурационного файла определения прикладных 
	элементов Ядра - guard-объектов, операций, операций-обработчиков.
-->
<xsd:schema 
	xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
	elementFormDefault="qualified"
	attributeFormDefault="unqualified"
	targetNamespace="http://www.croc.ru/Schemas/XmlFramework/Core/Config/ServerObjects/1.0" 
	xmlns="http://www.croc.ru/Schemas/XmlFramework/Core/Config/ServerObjects/1.0" 
	version="1.0"
>
	<!-- 
		Перечень всех серверных объектов - корневой элемент
	-->
	<xsd:element name="server-objects">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="assemblies">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="assembly" type="xsd:string" maxOccurs="unbounded"/>
							<!-- Имя сборки (указывать расширенее не нужно) -->
						</xsd:sequence>
					</xsd:complexType>
					<xsd:unique name="uniqueAssemblyName">
						<xsd:selector xpath="assembly"/>
						<xsd:field xpath="."/>
					</xsd:unique>
					<!-- Накладываем дополнительное ограничение - на одно событие один обработчик можно подписать не более одного раза -->
				</xsd:element>
				<xsd:element name="guards">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="guard" type="guardType" maxOccurs="unbounded"/>
							<!-- Описание Guard-а -->
						</xsd:sequence>
						<xsd:attribute name="default-connection" type="xsd:string" use="required"/>
						<!-- Имя соединения, используемого по умолчанию-->
					</xsd:complexType>
				</xsd:element>
				<xsd:element name="commands">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="command" type="commandType" maxOccurs="unbounded">
								<xsd:unique name="uniqueHandlerEventPair">
									<xsd:selector xpath="handle-event"/>
									<xsd:field xpath="@event"/>
									<xsd:field xpath="@handler-name"/>
								</xsd:unique>
								<xsd:unique name="uniqueHandlerSuppress">
									<xsd:selector xpath="suppress-event"/>
									<xsd:field xpath="@event"/>
								</xsd:unique>
								<!-- Накладываем дополнительное ограничение - на одно событие один обработчик можно подписать не более одного раза -->
								<!-- Накладываем дополнительное ограничение - от одного события можно отписаться только 1 раз -->
								<!-- Ссылка на имя обработчика события в описании операции-->
							</xsd:element>
						</xsd:sequence>
						<xsd:attribute name="default-guard" type="xsd:string" use="required"/>
						<xsd:attribute name="default-connection" type="xsd:string" use="required"/>
						<!-- Имя Guard-а, используемого по умолчанию-->
						<!-- Имя соединения, используемого по умолчанию-->
					</xsd:complexType>
					<xsd:unique name="CommandsKey">
						<xsd:selector xpath="command"/>
						<xsd:field xpath="@n"/>
					</xsd:unique>
					<xsd:keyref name="CommandsGuardsKeyRef" refer="GuardsKey">
						<xsd:selector xpath="commands"/>
						<xsd:field xpath="@default-guard"/>
					</xsd:keyref>
					<!-- Ключ, определяющий уникальные имена операций-->
					<!-- Ссылка на имя guard-а в описании операций-->
				</xsd:element>
				<xsd:element name="event-handlers" minOccurs="0">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="event-handler" type="event-handlerType" minOccurs="0" maxOccurs="unbounded">
								<xsd:unique name="uniqueHandlerEventName">
									<xsd:selector xpath="use-for"/>
									<xsd:field xpath="@event"/>
								</xsd:unique>
								<!-- Накладываем дополнительное ограничение - на одно событие один обработчик можно подписать не более одного раза -->
							</xsd:element>
						</xsd:sequence>
						<xsd:attribute name="default-connection" type="xsd:string" use="required"/>
					</xsd:complexType>
				</xsd:element>
				<!-- 
					Перечень сборок, в которых описаны классы серверных объектов 
				-->
				<!-- 
					Перечень Guard-ов
				-->
				<!-- 
					Перечень операций 
				-->
				<!-- 
					Перечень обработчиков событий 
				-->
			</xsd:sequence>
		</xsd:complexType>
		<xsd:unique name="GuardsKey">
			<xsd:selector xpath="guards/guard"/>
			<xsd:field xpath="@n"/>
		</xsd:unique>
		<xsd:unique name="EventHandlersKey">
			<xsd:selector xpath="event-handlers/event-handler"/>
			<xsd:field xpath="@n"/>
		</xsd:unique>
		<!-- 
			Ключ, определяющий уникальные имена Guard-ов
		-->
		<!-- 
			Ключ, определяющий уникальные имена обработчиков событий 
		-->
	</xsd:element>
	<!-- 
		Перечень событий, генерируемых ядром 
	-->
	<xsd:simpleType name="Events">
		<xsd:restriction base="xsd:NMTOKEN">
			<xsd:enumeration value="OnGuardQuery"/>
			<xsd:enumeration value="OnGetGuardRejection"/>
			<xsd:enumeration value="OnGetGuardPermission"/>
			<xsd:enumeration value="OnGuardFailed"/>
			<xsd:enumeration value="OnOperationStart"/>
			<xsd:enumeration value="OnOperationCompleted"/>
			<xsd:enumeration value="OnOperationFailed"/>
			<xsd:enumeration value="OnOperationSuspended"/>
			<xsd:enumeration value="OnOperationResume"/>
			<xsd:enumeration value="OnOperationTerminated"/>
			<xsd:enumeration value="OnSessionStart"/>
			<xsd:enumeration value="OnSessionStop"/>
			<xsd:enumeration value="OnApplicationStart"/>
		</xsd:restriction>
	</xsd:simpleType>
	<!-- 
		Базовый тип для описания серверных объектов 
	-->
	<xsd:complexType name="serverObject" abstract="true">
		<xsd:attribute name="n" type="xsd:NMTOKEN" use="required"/>
		<xsd:attribute name="class-name" type="xsd:string" use="required"/>
		<xsd:attribute name="connection" type="xsd:string"/>
		<!--		
			"Наименование"; используется для задания внутреннего наименования, 
			по которому далее осуществляется логическа ссылка на элемент; 
			корректность таких ссылок отслеживается при инициализации Ядра. 
			Задание атрибута обязательно.
		-->
		<!--
			Задает наименование .NET-типа - класса реализации сущности Ядра, 
			описываемого элементом. Задание атрибута обязательно.
		-->
		<!-- 
			Задает "ссылку" на описание элемента с данными, используемыми для 
			инициализации соединения с СУБД (см. x-net-config-schema.xml)
			Задание значения обязательно.
		-->
	</xsd:complexType>
	<!-- 
		Элемент, определяющий guard-объект приложения.
		(Не имеет дополнительных свойств по сравнению с serverObject)
	-->
	<xsd:complexType name="guardType">
		<xsd:complexContent>
			<xsd:extension base="serverObject"/>
		</xsd:complexContent>
	</xsd:complexType>
	<!-- 
		Тип описания операции 
	-->
	<xsd:complexType name="commandType">
		<xsd:complexContent>
			<xsd:extension base="serverObject">
				<xsd:sequence minOccurs="0" maxOccurs="unbounded">
					<xsd:choice>
						<xsd:element name="handle-event" minOccurs="0" maxOccurs="unbounded">
							<xsd:complexType>
								<xsd:attribute name="event" type="Events" use="required"/>
								<xsd:attribute name="handler-name" type="xsd:string" use="required"/>
								<!-- Название события  -->
								<!-- Внутреннее наименование обработчика - ссылка на описание -->
							</xsd:complexType>
						</xsd:element>
						<xsd:element name="suppress-event" minOccurs="0" maxOccurs="unbounded">
							<xsd:complexType>
								<xsd:attribute name="event" type="Events" use="required"/>
								<!-- Название события  -->
							</xsd:complexType>
						</xsd:element>
						<!-- Может переопределять обработчики некоторых событий -->
						<!-- Может отменять обработчики событий -->
					</xsd:choice>
				</xsd:sequence>
				<xsd:attribute name="d" type="xsd:string"/>
				<xsd:attribute name="is-public" type="xsd:boolean"/>
				<xsd:attribute name="guard-name" type="xsd:string"/>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>
	<!-- 
	
    		Элемент, описывающий операцию-обработчик событий Ядра
	 -->
	<xsd:complexType name="event-handlerType">
		<xsd:complexContent>
			<xsd:extension base="serverObject">
				<xsd:sequence>
					<xsd:element name="use-for" minOccurs="0" maxOccurs="unbounded">
						<xsd:complexType>
							<xsd:attribute name="event" type="Events" use="required"/>
							<!-- Название события -->
						</xsd:complexType>
					</xsd:element>
					<!-- Может содержать последовательность имен событий, для которых должен вызываться обработчик -->
				</xsd:sequence>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>
</xsd:schema>

=== SanSay157/IT8/IT.Web/Metadata/it-server-objects.xml
<?xml version="1.0" encoding="windows-1251"?>
<!--
	CROC XML Framework .NET
	КОНФИГУРАЦИОННЫЙ ФАЙЛ ОПРЕДЕЛЕНИЯ ПРИКЛАДНЫХ ЭЛЕМЕНТОВ ЯДРА
	
	Внимание! Файл описывает конфигурацию модельного приложения учебного курса 
	и может использоваться только как пример конфигурационного файла!
-->
<server-objects xmlns="http://www.croc.ru/Schemas/XmlFramework/Core/Config/ServerObjects/1.0" xsi:schemaLocation="http://www.croc.ru/Schemas/XmlFramework/Core/Config/ServerObjects/1.0 x-net-server-objects-schema.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <!-- ПЕРЕЧЕНЬ СБОРОК ПРИЛОЖЕНИЯ -->
  <assemblies>
    <assembly>Croc.XmlFramework.Commands</assembly>
    <assembly>Croc.XmlFramework.ReportService.Commands</assembly>
    <assembly>Croc.XmlFramework.ReportService</assembly>
    <assembly>Croc.XmlFramework.TransferService.Commands</assembly>
    <assembly>Croc.IncidentTracker.Commands</assembly>
  </assemblies>
  <!-- ПЕРЕЧЕНЬ GUARD-ОБЪЕКТОВ ПРИЛОЖЕНИЯ -->
  <guards default-connection="ROConnection">
    <guard n="CheckAppUser" class-name="Croc.IncidentTracker.Commands.Guards.CheckAppUserGuard"/>
    <guard n="ListAccessCheck" class-name="Croc.IncidentTracker.Commands.Guards.ListAccessCheckGuard" />
    <guard n="TreeAccessCheck" class-name="Croc.IncidentTracker.Commands.Guards.TreeAccessCheckGuard" />
  </guards>
  <!-- ПЕРЕЧЕНЬ ОПЕРАЦИЙ ПРИЛОЖЕНИЯ -->
  <commands default-connection="ROConnection" default-guard="CheckAppUser">
    <!--<command n="SendNotificationsAsync"
			d="Рассылка сообщений"
			class-name="Croc.IncidentTracker.Commands.FakeSendNotificationMailAsyncCommand"
			connection="RWConnection"
			is-public="false"
			/>-->

    <command n="GetKassBallance"
      d="Возвращает текущий балланс ДС в кассе"
      class-name="Croc.IncidentTracker.Commands.GetKassBallanceCommand"
      connection="RWConnection"
      is-public="true"
			/>
    
    <command n="CheckDeadlinedIncidents"
			d="Генерирует события для инцидетов с просроченным/надвигающимся дедлайном"
			class-name="Croc.IncidentTracker.Commands.CheckDeadlinedIncidentsCommand"
			connection="RWConnection"
			is-public="true"
			/>

    <command n="UserSubscriptionForEventClass"
			d="Управление подпиской пользователя"
			class-name="Croc.IncidentTracker.Commands.UserSubscriptionForEventClassCommand"
			connection="RWConnection"
			is-public="true"
			/>

    <command n="GetCurrentUserNavInfo"
			d="Получение данных, описывающих навигационные элементы, доступные для текущего пользователя"
			class-name="Croc.IncidentTracker.Commands.GetCurrentUserNavInfoCommand"
			connection="ROConnection"
			is-public="true"
			/>
    <command n="GetCurrentUserProfile"
			d="Получение данных объекта, описывающего настройки текущего пользователя"
			class-name="Croc.IncidentTracker.Commands.GetCurrentUserProfileCommand"
			connection="ROConnection"
			is-public="true"
			/>
    <command n="GetExpensesData"
			d="Получение детальных данных о затратах сотрудника за предыдущий, текущий месяц и текущий день"
			class-name="Croc.IncidentTracker.Commands.GetExpensesDataCommand"
			connection="ROConnection"
			is-public="true"
			/>
    <command n="DeleteUnusedObjects"
			d="Удаляет неиспользуемые объекты из БД"
			class-name="Croc.IncidentTracker.Commands.DeleteUnusedObjectsCommand"
			connection="RWConnection"
			is-public="true"
			/>
    <command n="JobsScheduler"
			d="Запускает планировщик заданий"
			class-name="Croc.IncidentTracker.Jobs.JobsSchedulerCommand"
			is-public="true"
			/>
    <command n="SaveObjectWithSignature"
			d="Сохраняет XML-объект или множество XML-объектов с добавлением подписи к определенным полям"
			class-name="Croc.IncidentTracker.Commands.SaveObjectWithSignatureCommand"
			connection="RWConnection"
			is-public="true"
			/>
    <command n="SaveTimeLossObject"
			class-name="Croc.IncidentTracker.Commands.SaveTimeLossObjectCommand"
			d="Сохраняет объекты Списание времени"
			connection="RWConnection"
			is-public="true"
			/>

    <command n="GetFilterTendersInfo"
			d="Получения данных для фильтра списка тендеров"
			class-name="Croc.IncidentTracker.Commands.GetFilterTendersInfoCommand"
			is-public="true"
			/>
    <command n="GetCurrentUserClientProfile"
			d="Получение xml-объекта с описанием текущего сотрудника-пользователя"
			class-name="Croc.IncidentTracker.Commands.GetCurrentUserClientProfileCommand"
			is-public="true"
			/>
    <command n="GetCurrentTime"
			d="Получение времени на сервере"
			class-name="Croc.XmlFramework.Commands.XGetCurrentTimeCommand"
			is-public="true"
			/>
    <command n="GetSoftwareVersions"
			d="Получение версий ПО на сервере"
			class-name="Croc.XmlFramework.Commands.XGetServerSoftwareVersionCommand"
			is-public="true"
			/>
    <command n="GetAssemblyVersions"
			d="Получение версий сборок на сервере"
			class-name="Croc.XmlFramework.Commands.XGetAssemblyVersionsCommand"
			is-public="true"
			/>
    <command n="GetCurrentUser"
			d="Возвращает информацию о пользователе, выполняющем данный запрос"
			class-name="Croc.XmlFramework.Commands.XGetCurrentUserCommand"
			is-public="true"
			/>
    <command n="GetListData"
			d="Возвращает XML-данные списка, отображаемые компонентой CROC.XListView с подстановкой общих параметрв"
			class-name="Croc.IncidentTracker.Commands.GetDataCommonCommand"
			is-public="true"
			guard-name="ListAccessCheck"
			/>
    <command n="XGetListData"
			d="Возвращает XML-данные списка, отображаемые компонентой CROC.XListView"
			class-name="Croc.XmlFramework.Commands.XGetListDataCommand"
			is-public="false"
			/>
    <command n="GetTreeData"
			d="Возвращает XML-данные иерархии, отображаемой компонентой CROC.XTreeView с подстановкой общих параметров"
			class-name="Croc.IncidentTracker.Commands.GetDataCommonCommand"
			is-public="true"
			guard-name="TreeAccessCheck"
			/>
    <command n="XGetTreeData"
			d="Возвращает XML-данные иерархии, отображаемой компонентой CROC.XTreeView"
			class-name="Croc.IncidentTracker.Commands.GetTreeDataEntryCommand"
			is-public="false"
			/>
    <command n="GetTreeMenu"
			d="Возвращает описание меню для заданного узла иерархии с подстановкой общих параметров"
			class-name="Croc.IncidentTracker.Commands.GetDataCommonCommand"
			is-public="true"
			/>
    <command n="XGetTreeMenu"
			d="Возвращает описание меню для заданного узла иерархии"
			class-name="Croc.IncidentTracker.Commands.GetTreeMenuEntryCommand"
			is-public="false"
			/>
    <command n="GetTreeNodeDrag"
			d="Возвращает описание операции переноса для заданного узла иерархии"
			class-name="Croc.XmlFramework.Extension.Commands.XXGetTreeNodeDragCommand"
			is-public="true"
			/>

    <command n="GetObject"
			d="Возвращает данные объекта, заданного или нового, в XML-формате"
			class-name="Croc.IncidentTracker.Commands.GetObjectCommand"
			is-public="true"
			/>
    <command n="GetObjects"
			d="Возвращает список запрошенных объектов"
			class-name="Croc.IncidentTracker.Commands.GetObjectsCommand"
			is-public="true"
			/>
    <command n="GetProperty"
			d="Возвращает данные свойства объекта из БД"
			class-name="Croc.IncidentTracker.Commands.GetPropertyCommand"
			is-public="true"
			/>
    <command n="GetTypeMD"
			d="Возвращает метаданные для заданного ds-типа"
			class-name="Croc.XmlFramework.Commands.XGetTypeMDCommand"
			is-public="true"
			/>
    <command n="GetMetadataVersion"
			d="Возвращает информацию о версии метаданных приложения"
			class-name="Croc.XmlFramework.Commands.XGetMetadataVersionCommand"
			is-public="true"
			/>
    <command n="GetMetadataRoot"
			d="Возвращает корневой элемент метаданных приложения"
			class-name="Croc.XmlFramework.Commands.XGetMetadataRootCommand"
			is-public="true"
			/>
    <command n="GetMetadata"
			d="Возвращает все метаданные приложения"
			class-name="Croc.XmlFramework.Commands.XGetMetadataCommand"
			is-public="true"
			/>
    <command n="SaveObject"
			d="Сохраняет XML-объект или множество XML-объектов"
			class-name="Croc.IncidentTracker.Commands.SaveObjectCommand"
			connection="RWConnection"
			is-public="true"
			/>
    <command n="ChunkUpload"
			d="Загружает в БД данные 'кусками'"
			class-name="Croc.XmlFramework.Commands.XChunkUploadCommand"
			connection="RWConnection"
			is-public="true"
			/>
    <command n="ChunkPurge"
			d="Удаляет данные, загруженные посредством ChunkUpload"
			class-name="Croc.XmlFramework.Commands.XChunkPurgeCommand"
			connection="RWConnection"
			is-public="true"
			/>
    <command n="DeleteObject"
			d="Удаляет данные заданного ds-объекта из БД"
			class-name="Croc.IncidentTracker.Commands.DeleteObjectCommand"
			connection="RWConnection"
			is-public="true"
			/>
    <command n="GetObjectsRights"
			d="Проверка наличия прав на объекты"
			class-name="Croc.IncidentTracker.Commands.GetObjectsRightsCommand"
			is-public="true"
			/>
    <command n="GetObjectsRightsEx"
			d="Проверка наличия прав на объекты в датаграмме"
			class-name="Croc.IncidentTracker.Commands.GetObjectsRightsExCommand"
			is-public="true"
			/>
    <command n="ExecuteDataSource"
			d="Выполнение выделенного источника данных"
			class-name="Croc.IncidentTracker.Commands.GetDataCommonCommand"
			is-public="true"
			/>
    <command n="XExecuteDataSource"
			d="Выполнение выделенного источника данных"
			class-name="Croc.XmlFramework.Commands.XExecuteDataSourceCommand"
			connection="RWConnection"
			is-public="false"
			/>
    <command n="GetConfigElement"
			d="Получение XML-элемента конфигурационного файла"
			class-name="Croc.XmlFramework.Commands.XGetConfigElementCommand"
			is-public="true"
			/>
    <command n="Reset"
			d="Сброс сервера"
			class-name="Croc.XmlFramework.Commands.XResetCommand"
			is-public="true"
			/>
    <command n="EmployeeLocatorInCompanyTree"
			class-name="Croc.IncidentTracker.Commands.EmployeeLocatorInCompanyTreeCommand"
			is-public="true"
			/>
    <command n="IncidentLocatorInTree"
			class-name="Croc.IncidentTracker.Commands.IncidentLocatorInTreeCommand"
			is-public="true"
			/>
