=== SanSay157/IT8/IT.Services/Schemas/it-common-service-data-schema.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!--
********************************************************************************
	Система оперативного управления проектами - Incident Tracker
	ЗАО КРОК инкорпорейтед, 2005
********************************************************************************
	Определение формата XML-данных, возвращаемых в результате вызвов методов
	общего Web-сервиса системы (CommonService)
-->
<xsd:schema 
	xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
	xmlns="http://www.croc.ru/Schemas/IncidentTracker/WebServices/CommonServiceData/1.0" 
	targetNamespace="http://www.croc.ru/Schemas/IncidentTracker/WebServices/CommonServiceData/1.0" 
	elementFormDefault="qualified" 
	attributeFormDefault="unqualified" 
	version="1.0" 
	id="it-common-service-data-schema"	
>
	<!-- 

	-->
	<xsd:complexType name="tConstantValue">
		<xsd:all>
			<xsd:element name="constant" type="xsd:string" minOccurs="1" maxOccurs="1"/>
			<xsd:element name="value" minOccurs="1" maxOccurs="1"/>
			<xsd:element name="at-date" type="xsd:date" minOccurs="1" maxOccurs="1"/>
		</xsd:all>
	</xsd:complexType>
	<!--

		Определение общего способа идентификации объектов
		Комплексный тип, задает идентифкацию объекта, через атрибуты interal-id 
		и external-id
	-->
	<xsd:complexType name="tObjectIdentification">
		<xsd:attribute name="internal-id" type="xsd:string" use="required">
			<xsd:annotation>
				<xsd:documentation>Внутренний идентификатор объекта в системе Incident Tracker</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
		<xsd:attribute name="external-id" type="xsd:string" use="optional">
			<xsd:annotation>
				<xsd:documentation>Идентификатор объекта во внешней системе (в общем случае - во внешней системе ведения нормативной справочной информации - НСИ)</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
	</xsd:complexType>
	<!--
		
	-->
	<xsd:complexType name="tEmployeeRef">
		<xsd:complexContent>
			<xsd:extension base="tObjectIdentification">
				<xsd:sequence>
					<xsd:element name="full-name" type="xsd:string" minOccurs="1" maxOccurs="1"/>
				</xsd:sequence>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>
	<!--

	-->
	<xsd:complexType name="tOrganizationBase">
		<xsd:annotation>
			<xsd:documentation>Определение общих атрибутов и элементов, используемых для предоставления данных по организации</xsd:documentation>
		</xsd:annotation>
		<xsd:complexContent>
			<xsd:extension base="tObjectIdentification">
				<xsd:sequence>
					<xsd:element name="short-name" type="xsd:string" minOccurs="1" maxOccurs="1"/>
					<xsd:element name="full-name" type="xsd:string"/>
					<xsd:element name="account-manager" type="tEmployeeRef"/>
				</xsd:sequence>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>
	<!--

	-->
	<xsd:complexType name="tOrganizationsList">
		<xsd:sequence>
			<xsd:element name="organization" type="tOrganizationBase" minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="tOrganizationInfo">
		<xsd:complexContent>
			<xsd:extension base="tOrganizationBase">
				<xsd:sequence>
					<xsd:element name="comment" type="xsd:string"/>
				</xsd:sequence>
				<xsd:attribute name="is-it-owner" type="xsd:boolean"/>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>
	<!--

	-->
	<xsd:complexType name="tDepartmentBase">
		<xsd:annotation>
			<xsd:documentation>Определение общих атрибутов и элементов, используемых для предоставления данных о подразделени организации</xsd:documentation>
		</xsd:annotation>
		<xsd:complexContent>
			<xsd:extension base="tObjectIdentification">
				<xsd:sequence>
					<xsd:element name="short-name" type="xsd:string" minOccurs="1" maxOccurs="1"/>
					<xsd:element name="full-name"  type="xsd:string" minOccurs="1" maxOccurs="1"/>
					<xsd:element name="director" type="tEmployeeRef" minOccurs="0" maxOccurs="1"/>
					<xsd:element name="higher-department" type="tObjectIdentification" minOccurs="0" maxOccurs="1"/>
				</xsd:sequence>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>
	<!--

	-->
	<xsd:complexType name="tDepartmentsList">
		<xsd:sequence>
			<xsd:element name="department" type="tDepartmentBase"/>
		</xsd:sequence>
	</xsd:complexType>
	<!--

	-->
	<xsd:complexType name="tDepartmentInfo">
		<xsd:complexContent>
			<xsd:extension base="tDepartmentBase">
				<xsd:sequence>
					<xsd:element name="comment" type="xsd:string"/>
				</xsd:sequence>
				<xsd:attribute name="is-it-accountable" type="xsd:boolean" use="required"/>
				<xsd:attribute name="has-it-subdivision" type="xsd:boolean" use="required"/>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>
	<!--

	-->
	<xsd:complexType name="tEmployeesList">
		<xsd:annotation>
			<xsd:documentation></xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="employee" minOccurs="0" maxOccurs="unbounded">
				<xsd:complexType>
					<xsd:complexContent>
						<xsd:extension base="tEmployeeRef">
							<xsd:sequence>
								<xsd:element name="login" type="xsd:string" minOccurs="1" maxOccurs="1"/>
								<xsd:element name="department-member" type="tObjectIdentification" minOccurs="0" maxOccurs="1"/>
							</xsd:sequence>
						</xsd:extension>
					</xsd:complexContent>
				</xsd:complexType>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<!--

	-->
	<xsd:complexType name="tEmployeeInfo">
		<xsd:annotation>
			<xsd:documentation></xsd:documentation>
		</xsd:annotation>
		<xsd:complexContent>
			<xsd:extension base="tObjectIdentification">
				<xsd:sequence>
					<xsd:element name="first-name" type="xsd:string" minOccurs="1" maxOccurs="1"/>
					<xsd:element name="middle-name" type="xsd:string" minOccurs="1" maxOccurs="1"/>
					<xsd:element name="last-name" type="xsd:string" minOccurs="1" maxOccurs="1"/>
					<xsd:element name="login" type="xsd:string" minOccurs="1" maxOccurs="1"/>
					<xsd:element name="begin-work" type="xsd:date" minOccurs="1" maxOccurs="1"/>
					<xsd:element name="end-work" type="xsd:date" minOccurs="0" maxOccurs="1"/>
					<xsd:element name="phones" type="xsd:string" minOccurs="1" maxOccurs="1"/>
					<xsd:element name="phones-add" type="xsd:string" minOccurs="1" maxOccurs="1"/>
					<xsd:element name="e-mail" type="xsd:string" minOccurs="1" maxOccurs="1"/>
					<xsd:element name="mobile-phone" type="xsd:string" minOccurs="1" maxOccurs="1"/>
					<xsd:element name="post-address" type="xsd:string" minOccurs="1" maxOccurs="1"/>
					<xsd:element name="pager-phone" type="xsd:string" minOccurs="1" maxOccurs="1"/>
					<xsd:element name="pager-number" type="xsd:string" minOccurs="1" maxOccurs="1"/>
					<xsd:element name="department-member" type="tObjectIdentification"/>
				</xsd:sequence>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>
	<!--

	-->
	<xsd:complexType name="tDirectionBase">
		<xsd:annotation>
			<xsd:documentation></xsd:documentation>
		</xsd:annotation>
		<xsd:complexContent>
			<xsd:extension base="tObjectIdentification">
				<xsd:sequence>
					<xsd:element name="name" type="xsd:string" minOccurs="1" maxOccurs="1"/>
				</xsd:sequence>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>
	<!--
	
	-->
	<xsd:complexType name="tDirectionsList">
		<xsd:sequence>
			<xsd:choice>
				<xsd:element name="direction" type="tDirectionBase" minOccurs="0" maxOccurs="unbounded"/>
				<xsd:element name="apply-department" minOccurs="0" maxOccurs="unbounded">
					<xsd:complexType>
						<xsd:complexContent>
							<xsd:extension base="tDepartmentBase">
								<xsd:sequence>
									<xsd:element name="apply-direction" type="tDirectionBase" minOccurs="0" maxOccurs="unbounded"/>
								</xsd:sequence>
							</xsd:extension>
						</xsd:complexContent>
					</xsd:complexType>
				</xsd:element>
			</xsd:choice>
		</xsd:sequence>
	</xsd:complexType>
	<!--

	-->
	<xsd:element name="constant-value" type="tConstantValue"/>
	<xsd:element name="organizations-list" type="tOrganizationsList"/>
	<xsd:element name="organization-info" type="tOrganizationInfo"/>
	<xsd:element name="departments-list" type="tDepartmentsList"/>
	<xsd:element name="department-info" type="tDepartmentInfo"/>
	<xsd:element name="employees-list" type="tEmployeesList"/>
	<xsd:element name="employee-info" type="tEmployeeInfo"/>
	<xsd:element name="directions-list" type="tDirectionsList"/>
	
	<!--
		ВРЕМЕННОЕ ОПРЕДЕЛЕНИЕ
		(для выполнения проверки по схеме для XML-документа с примерами всех форматов данных)
	-->
	<xsd:element name="example-data">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="constant-value" type="tConstantValue"/>
				<xsd:element name="organizations-list" type="tOrganizationsList"/>
				<xsd:element name="organization-info" type="tOrganizationInfo"/>
				<xsd:element name="departments-list" type="tDepartmentsList"/>
				<xsd:element name="department-info" type="tDepartmentInfo"/>
				<xsd:element name="employees-list" type="tEmployeesList"/>
				<xsd:element name="employee-info" type="tEmployeeInfo"/>
				<xsd:element name="directions-list" type="tDirectionsList" maxOccurs="unbounded"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
</xsd:schema>

=== SanSay157/IT8/IT.Services/Schemas/it-common-service-data-schema.example.xml
<?xml version="1.0" encoding="windows-1251"?>
<example-data
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xmlns:dt="urn:schemas-microsoft-com:datatypes" 
	xmlns="http://www.croc.ru/Schemas/IncidentTracker/WebServices/CommonServiceData/1.0"
	xsi:schemaLocation="http://www.croc.ru/Schemas/IncidentTracker/WebServices/CommonServiceData/1.0 it-common-service-data-schema.xsd"
>
	<!-- 

		Пример значения константы системы Incident Tracker; 
		результат вызова методов GetConstValue, GetCurrentConstValue 
	-->
	<constant-value>
		<constant>SecuredExternalSystemBaseURL</constant>
		<value>https://it.croc.ru/it/</value>
		<at-date>2008-12-23</at-date>
	</constant-value>
	<!-- 

		Пример данных списка организаций; 
		результат вызова метода GetOrganizationsList 
	-->
	<organizations-list>
		<organization internal-id="12345678-90ab-cdef-1234-567890abcdf0" external-id="12345">
			<short-name>Специальная Компания</short-name>
			<full-name>Специальная Компания, ЗАО</full-name>
			<account-manager internal-id="12345678-90ab-cdef-1234-567890abcdf0" external-id="12345">
				<full-name>Иванов Иван Иванович</full-name>
			</account-manager>
		</organization>
	</organizations-list>
	<!--

		Пример детальных данных одной организации;
		результат вызова метода GetOrganizationInfo
	-->
	<organization-info internal-id="12345678-90ab-cdef-1234-567890abcdf0" external-id="12345" is-it-owner="false">
		<short-name>Специальная Компания</short-name>
		<full-name>Специальная Компания, ЗАО</full-name>
		<account-manager internal-id="12345678-90ab-cdef-1234-567890abcdf0" external-id="12345">
			<full-name>Иванов Иван Иванович</full-name>
		</account-manager>
		<comment>Специальная Компания работает на рынке с 1999 года</comment>
	</organization-info>
	<!-- 

		Пример данных списка подразделений заданной организации;
		результат вызова метода GetDepartmentsList, GetSubDepartmentsList
	-->
	<departments-list>
		<department internal-id="12345678-90ab-cdef-1234-567890abcdf0" external-id="12345">
			<short-name>ДИТ</short-name>
			<full-name>Департамент Информационных Технологий</full-name>
			<director internal-id="12345678-90ab-cdef-1234-567890abcdf0" external-id="12345">
				<full-name>Владимиров Владимир Владимирович</full-name>
			</director>
			<!-- идентификаторы вышестоящего подразделения; если такового нет, элемент не задается -->
			<higher-department internal-id="12345678-90ab-cdef-1234-567890abcdf0" external-id="12345"/>
		</department>
	</departments-list>
	<!-- 

		Пример детальных данных одного подразделения;
		результат вызова метода GetDepartmentInfo
	-->
	<department-info internal-id="12345678-90ab-cdef-1234-567890abcdf0" external-id="12345" is-it-accountable="true" has-it-subdivision="true">
		<short-name>ДИТ</short-name>
		<full-name>Департамент Информационных Технологий</full-name>
		<director internal-id="12345678-90ab-cdef-1234-567890abcdf0" external-id="12345">
			<full-name>Владимиров Владимир Владимирович</full-name>
		</director>
		<!-- идентификаторы вышестоящего подразделения; если такового нет, элемент не задается -->
		<higher-department internal-id="12345678-90ab-cdef-1234-567890abcdf0" external-id="12345"/>
		<comment>Комментарий: является как центром затрат, так и центром прибыли</comment>
	</department-info>
	<!--

		Пример данных списка сотрудников заданного подразделения / организации;
		результат вызова метода GetEmployeesList
	-->
	<employees-list>
		<employee internal-id="12345678-90ab-cdef-1234-567890abcdf0" external-id="12345">
			<full-name>Петров Петр Петрович</full-name>
			<login>SC\PetrPetrov</login>
			<department-member internal-id="12345678-90ab-cdef-1234-567890abcdf0" external-id="12345"/>
		</employee>
	</employees-list>
	<!-- 

		Пример детальных данных одного сотрудника;
		результат вызова метода GetEmployeeInfo
	-->
	<employee-info internal-id="12345678-90ab-cdef-1234-567890abcdf0" external-id="12345">
		<first-name>Петр</first-name>
		<middle-name>Петрович</middle-name>
		<last-name>Петров</last-name>
		<login>SC\PetrPetrov</login>
		<begin-work>2000-01-01</begin-work>
		<!-- Дата завершения работы в организации; если сотрудник еще работает, элемент пустой -->
		<end-work>2005-06-01</end-work>
		<phones>123-45-67</phones>
		<phones-add>1234</phones-add>
		<e-mail>PetrPetrov@sc.ru</e-mail>
		<mobile-phone>8-916-1234567</mobile-phone>
		<post-address>Москва, а/я 12345, до востребования</post-address>
		<pager-phone>765-43-21</pager-phone>
		<pager-number>1098</pager-number>
		<department-member internal-id="12345678-90ab-cdef-1234-567890abcdf0" external-id="12345"/>
	</employee-info>
	<!-- 

		Пример данных списка описаний направлений деятельности;
		результат вызова метода GetDirectionsList
	-->
	<directions-list>
		<direction internal-id="12345678-90ab-cdef-1234-567890abcdf0" external-id="12345">
			<name>Разработка заказного программного обеспечения</name>
		</direction>
		<direction internal-id="12345678-90ab-cdef-1234-567890abcdf0" external-id="12345">
			<name>Консультации</name>
		</direction>
		<direction internal-id="12345678-90ab-cdef-1234-567890abcdf0" external-id="12345">
			<name>Сопровождение покупного программного обеспечения</name>
		</direction>
	</directions-list>
	<!--

		Пример данных списка описаний направления деятельности, прменимых
		в заданном подразделении (организации); 
		результат вызова метода GetHandledDirectionsList
	-->
	<directions-list>
		<apply-department internal-id="12345678-90ab-cdef-1234-567890abcdf0" external-id="12345">
			<short-name>ДИТ</short-name>
			<full-name>Департамент Информационных Технологий</full-name>
			<director internal-id="12345678-90ab-cdef-1234-567890abcdf0" external-id="12345">
				<full-name>Владимиров Владимир Владимирович</full-name>
			</director>
			<apply-direction internal-id="12345678-90ab-cdef-1234-567890abcdf0" external-id="12345">
				<name>Разработка заказного программного обеспечения</name>
			</apply-direction>
			<apply-direction internal-id="12345678-90ab-cdef-1234-567890abcdf0" external-id="12345">
				<name>Консультации</name>
			</apply-direction>
		</apply-department>
	</directions-list>
</example-data>
